version: '3'

services:
  db:
    container_name: treemenu_db
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - treemenu_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 10


  app:
    container_name: treemenu_app
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/static/
    ports:
      - "8000:8000"


  nginx:
    container_name: treemenu_nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/app/static/
    depends_on:
      app:
        condition: service_started
    ports:
      - "80:80"


volumes:
  treemenu_data:
    driver: local
  static_volume:
    driver: local
